// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using projeto.Data.Repositories;

#nullable disable

namespace AS_FINAL.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230627013440_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.7");

            modelBuilder.Entity("AS_FINAL.Domain.Autor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LivroId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LivroId");

                    b.ToTable("Autores");
                });

            modelBuilder.Entity("AS_FINAL.Domain.Livro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Livros");
                });

            modelBuilder.Entity("AS_FINAL.Domain.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("AS_FINAL.Domain.Autor", b =>
                {
                    b.HasOne("AS_FINAL.Domain.Livro", null)
                        .WithMany("Autores")
                        .HasForeignKey("LivroId");
                });

            modelBuilder.Entity("AS_FINAL.Domain.Livro", b =>
                {
                    b.HasOne("AS_FINAL.Domain.Usuario", null)
                        .WithMany("LivrosEmprestados")
                        .HasForeignKey("UsuarioId");
                });

            modelBuilder.Entity("AS_FINAL.Domain.Livro", b =>
                {
                    b.Navigation("Autores");
                });

            modelBuilder.Entity("AS_FINAL.Domain.Usuario", b =>
                {
                    b.Navigation("LivrosEmprestados");
                });
#pragma warning restore 612, 618
        }
    }
}
